trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - docs

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: environment
    value: dev
  - template: templates/variables.yaml

stages:
  - template: templates/workflow.yaml
