trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml

stages:
  - stage: BuildAndPushProxy
    displayName: Build and push Data Sharing Proxy image
    jobs:
      - template: templates/build-and-push.yaml
        parameters:
          displayName: Data Sharing proxy
          repository: giga-data-sharing-proxy
          dockerfile: $(Build.SourcesDirectory)/proxy.prod.Dockerfile

  - stage: BuildAndPushDeltaSharing
    displayName: Build and push Delta Sharing server image
    dependsOn: [ ]
    jobs:
      - template: templates/build-and-push.yaml
        parameters:
          displayName: Delta Sharing server
          repository: giga-data-sharing-delta
          dockerfile: $(Build.SourcesDirectory)/delta.prod.Dockerfile

  - stage: CreateConfig
    displayName: Create/update K8s configuration resources
    dependsOn: [ ]
    jobs:
      - template: templates/create-config.yaml

  - stage: Deploy
    displayName: Deploy Data Sharing
    dependsOn:
      - BuildAndPushProxy
      - BuildAndPushDeltaSharing
      - CreateConfig
    jobs:
      - template: templates/helm-deploy.yaml
