networks:
  default:
    name: giga-dataops
    external: true

volumes:
  db-data:

services:
  delta:
    build:
      context: .
      dockerfile: delta.dev.Dockerfile
    image: unicef/giga-data-sharing/delta-sharing
    restart: unless-stopped
    init: true
    env_file: .env
    ports:
      - "8890:8890"
    volumes:
      - ./conf:/app/conf

  proxy:
    build:
      context: .
      dockerfile: proxy.dev.Dockerfile
    image: unicef/giga-data-sharing/proxy
    restart: unless-stopped
    init: true
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./.venv-docker:/app/.venv

  db:
    image: bitnami/postgresql:16
    restart: unless-stopped
    init: true
    env_file: .env
    volumes:
      - db-data:/bitnami/postgresql
