networks:
  default:
    name: giga-dataops
    external: true

services:
  delta:
    build:
      context: .
      dockerfile: delta.dev.Dockerfile
    image: unicef/giga-data-sharing/delta-sharing
    restart: unless-stopped
    init: true
    env_file: .env
    platform: linux/amd64
    ports:
      - "8890:8890"
    volumes:
      - ./conf:/app/conf

  proxy:
    build:
      context: .
      dockerfile: proxy.dev.Dockerfile
    image: unicef/giga-data-sharing/proxy
    restart: unless-stopped
    init: true
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
