networks:
  default:
    name: giga-dataops
    external: true

services:
  sharing-server:
    restart: unless-stopped
    init: true
    image: deltaio/delta-sharing-server:0.6.7
    env_file: .env
    platform: linux/amd64
    command:
      - --config
      - /opt/docker/conf/delta-sharing-server-config.yml
    ports:
      - "8890:8890"
    volumes:
      - ./conf:/opt/docker/conf

  sharing-proxy:
    build: .
    image: unicef/giga-data-sharing/proxy
    restart: unless-stopped
    init: true
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
