services:
  server:
    restart: unless-stopped
    init: true
    image: deltaio/delta-sharing-server:0.6.7
    platform: linux/amd64
    command:
      - --config
      - /opt/docker/conf/delta-sharing-server-config.yml
    ports:
      - "8890:8890"
    volumes:
      - ./conf:/opt/docker/conf
