jobs:
  - deployment: Deploy
    displayName: Deploy Data Sharing
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Helm deploy Data Sharing Delta
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: infra/helm/data-sharing-delta
                releaseName: data-sharing-delta
                namespace: $(kubernetesNamespace)
                arguments: >
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-data-sharing-delta"
                  --set image.tag="$(Build.SourceVersion)"

            - task: HelmDeploy@0
              displayName: Helm deploy Data Sharing proxy
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: infra/helm/data-sharing-proxy
                releaseName: data-sharing-proxy
                namespace: $(kubernetesNamespace)
                arguments: >
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-data-sharing-proxy"
                  --set image.tag="$(Build.SourceVersion)"
                  --set ingress.enabled=true
                  --set ingress.hosts[0].host="$(ingressHost)"
                  --set ingress.hosts[0].paths[0].path="/"
                  --set ingress.hosts[0].paths[0].pathType=Exact
