apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "data-sharing-proxy.fullname" . }}-init-wait-db"
  labels:
    {{- include "data-sharing-proxy.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: "{{ include "data-sharing-proxy.fullname" . }}-init-wait-db"
          image: bitnami/postgresql:16.1.0-debian-11-r13
          command:
            - /bin/sh
            - -c
            - >
              until pg_isready
              --host $DB_HOST
              --port 5432
              --username $POSTGRESQL_USERNAME;
              do echo waiting for database;
              sleep 2;
              done;
          envFrom:
            {{- range .Values.envSecrets }}
            - secretRef:
              {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- range .Values.envConfigMaps }}
            - configMapRef:
              {{- toYaml . | nindent 16 }}
            {{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "data-sharing-proxy.fullname" . }}-init-db-migrations"
  labels:
      {{- include "data-sharing-proxy.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: "{{ include "data-sharing-proxy.fullname" . }}-init-db-migrations"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/bash
            - -c
            - alembic upgrade head
          envFrom:
            {{- range .Values.envSecrets }}
            - secretRef:
              {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- range .Values.envConfigMaps }}
            - configMapRef:
              {{- toYaml . | nindent 16 }}
            {{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "data-sharing-proxy.fullname" . }}-init-db-fixtures"
  labels:
      {{- include "data-sharing-proxy.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: "{{ include "data-sharing-proxy.fullname" . }}-init-db-fixtures"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/bash
            - -c
            - python -m scripts.load_fixtures roles api_keys
          envFrom:
            {{- range .Values.envSecrets }}
            - secretRef:
              {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- range .Values.envConfigMaps }}
            - configMapRef:
              {{- toYaml . | nindent 16 }}
            {{- end }}
