apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ include "data-sharing-proxy.fullname" . }}-pdb"
spec:
  selector:
    matchLabels:
      {{- include "data-sharing-proxy.selectorLabels" . | nindent 6 }}
  minAvailable: 50%
